version: '3.9'
services:
  node-api:
    build: ./node-api
    env_file:
      - ./node-api/.env
    ports:
      - '3000:3000'
  ai-service:
    build: ./ai-service
    env_file:
      - ./ai-service/.env
    ports:
      - '8000:8000'
